version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nestjs-api

  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: "npm run start:dev"

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  static-files:
    image: nginx:latest
    container_name: static-files
    volumes:
      - ./assets:/usr/share/nginx/html:ro
    ports:
      - "2000:2000"

volumes:
  db-data:

networks:
  default:
    external: true
    name: proxy-network